services:
  mkdocs:
    build: .
    container_name: ms-alz-workshop-docs
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for live reloading during development
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
